//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageValidation.Client.ServiceReferenceOnline {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceOnline.IImageValidationService")]
    public interface IImageValidationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageValidationService/ValidateUser", ReplyAction="http://tempuri.org/IImageValidationService/ValidateUserResponse")]
        ImageValidation.Core.Users ValidateUser(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageValidationService/SaveAccountHistory", ReplyAction="http://tempuri.org/IImageValidationService/SaveAccountHistoryResponse")]
        bool SaveAccountHistory(ImageValidation.Core.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageValidationService/CheckUsernameExists", ReplyAction="http://tempuri.org/IImageValidationService/CheckUsernameExistsResponse")]
        int CheckUsernameExists(ImageValidation.Core.Users ObjUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageValidationService/SaveFailedLogon", ReplyAction="http://tempuri.org/IImageValidationService/SaveFailedLogonResponse")]
        bool SaveFailedLogon(ImageValidation.Core.Users ObjUsers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageValidationServiceChannel : ImageValidation.Client.ServiceReferenceOnline.IImageValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageValidationServiceClient : System.ServiceModel.ClientBase<ImageValidation.Client.ServiceReferenceOnline.IImageValidationService>, ImageValidation.Client.ServiceReferenceOnline.IImageValidationService {
        
        public ImageValidationServiceClient() {
        }
        
        public ImageValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ImageValidation.Core.Users ValidateUser(string Username, string Password) {
            return base.Channel.ValidateUser(Username, Password);
        }
        
        public bool SaveAccountHistory(ImageValidation.Core.Users users) {
            return base.Channel.SaveAccountHistory(users);
        }
        
        public int CheckUsernameExists(ImageValidation.Core.Users ObjUser) {
            return base.Channel.CheckUsernameExists(ObjUser);
        }
        
        public bool SaveFailedLogon(ImageValidation.Core.Users ObjUsers) {
            return base.Channel.SaveFailedLogon(ObjUsers);
        }
    }
}
